spring:
  h2:
    console:
      enabled: true
      path: /h2
#  datasource:
#    url: jdbc:h2:mem:test
  datasource:
    url: jdbc:mysql://${AWS RDS Endpoint}/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: ${MYSQL_SECRET}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
    open-in-view: true

  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
  security:
    oauth2:
      client:
        registration:
          google:
            clientId : ${GOOGLE_CLIENT_ID}
            clientSecret : ${GOOGLE_SECRET}
            scope:
              - email
              - profile

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
mail:
  address:
    admin: admin@gmail.com    # jwt 사용할때 필요

jwt:
  key: ${JWT_SECRET_KEY}   # jwt 사용할때 필요
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420

api:
  key: ${api.key}